//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectOnTopMortgage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestaCallBack
    {
        public string Name { get; set; }
        public string Email { get; set; }
        public int Phone { get; set; }
        public string BestTimeToCall { get; set; }
        public int Id { get; set; }
    }
}
